-- The city row for Osijek. GENERATED by tools/cartography/add_city.py.
--
-- `active` is false on purpose: this says the city exists and has a map, not
-- that it is open. Opening it is a decision somebody makes, in the console.
insert into public.cities (name, country_code, timezone, centroid, active)
values (
  'Osijek', 'HR', 'Europe/Zagreb',
  extensions.ST_Point(18.695369, 45.554879, 4326)::extensions.geography,
  false
)
on conflict (name, country_code) do update set
  timezone = excluded.timezone, centroid = excluded.centroid;
